import React, { useState } from "react";
import { Link } from "react-router-dom";
import "../App.css";

function NewEntry() {
	//id is autogenerated
	const [entry, setEntry] = useState({
		date: "",
		title: "",
		mood: "",
		entry_text: "",
		moment_of_joy: "",
	});

	const { date, title, mood, entry_text, moment_of_joy } = entry;

	const handleInputChange = (e) => {
		const { value, name } = e.target;
		setEntry((state) => ({ ...state, [name]: value }));
	};

	//post into journal entries table
	const handleSubmit = async (e) => {
		try {
			const res = await fetch("/journal_entries", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify(entry),
			});
			const data = await res.json();
			setEntry(data);
		} catch (err) {
			console.log(err);
		}
	};

	return (
		<div>
			<div className="container bg-light shadow mt-4">
				<form onSubmit={handleSubmit}>
					<h3 className="darker">New Journal Entry</h3> <hr />
					<div className="row">
						<div className="col-3">
							<label htmlFor="date">Date</label> <br />
							<input
								className="form-control"
								name="date"
								type="date"
								value={date}
								onChange={handleInputChange}
								required
							/>
						</div>
						<div className="col-6">
							<label htmlFor="title">Title</label> <br />
							<input
								className="form-control"
								name="title"
								type="text"
								value={title}
								onChange={handleInputChange}
								minLength="5"
								required
							/>{" "}
						</div>
						<div className="col-6">
							<label  className="m-4" htmlFor="select_menu">Today I feel</label>
							<select
						className="btn bg-test5 text-light dropdown-toggle"
						name="mood"
						onChange={handleInputChange}
						value={mood}
						required
					>
						<option value="Happy">Happy</option>
						<option value="Hopeful">Hopeful</option>
						<option value="Optmistic">Optmistic</option>
						<option value="Tired">
							Tired
						</option>
						<option value="Anxious">
							Anxious
						</option>
						<option value="Disconnected">
							Disconnected
						</option>
						<option value="Angry">
							Angry
						</option>
						<option value="Sad">
					       Sad
						</option>
						<option value="Depressed">
							Depressed
						</option>
					</select>
						</div>
					</div>
					<div className="row">
						<div>
							<label>Entry</label> <br />
							<textarea
								className="form-control"
								name="entry_text"
								value={entry_text}
								onChange={handleInputChange}
							/>
						</div>
					</div>
					<div className="row">
						<div>
							<label>Moment of joy</label>
							<input
								className="form-control"
								name="moment_of_joy"
								type="text"
								value={moment_of_joy}
								onChange={handleInputChange}
							/>
						</div>
					</div>{" "}
					<br />
					<button className="btn btn-test6 bg-test6">Submit</button>{" "}
					<Link to={`/journal`}>
						<button className="btn bg-test6 btn-test6">
							Go Back to My Journal{" "}
						</button>
					</Link>
				</form>
				<br />
			</div>
			<br />
		</div>
	);
}

export default NewEntry;
